//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace systems.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CatalogEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CatalogEntities object using the connection string found in the 'CatalogEntities' section of the application configuration file.
        /// </summary>
        public CatalogEntities() : base("name=CatalogEntities", "CatalogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CatalogEntities object.
        /// </summary>
        public CatalogEntities(string connectionString) : base(connectionString, "CatalogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CatalogEntities object.
        /// </summary>
        public CatalogEntities(EntityConnection connection) : base(connection, "CatalogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CatalogBaseCours> CatalogBaseCourses
        {
            get
            {
                if ((_CatalogBaseCourses == null))
                {
                    _CatalogBaseCourses = base.CreateObjectSet<CatalogBaseCours>("CatalogBaseCourses");
                }
                return _CatalogBaseCourses;
            }
        }
        private ObjectSet<CatalogBaseCours> _CatalogBaseCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ESFCours> ESFCourses
        {
            get
            {
                if ((_ESFCourses == null))
                {
                    _ESFCourses = base.CreateObjectSet<ESFCours>("ESFCourses");
                }
                return _ESFCourses;
            }
        }
        private ObjectSet<ESFCours> _ESFCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SUCours> SUCourses
        {
            get
            {
                if ((_SUCourses == null))
                {
                    _SUCourses = base.CreateObjectSet<SUCours>("SUCourses");
                }
                return _SUCourses;
            }
        }
        private ObjectSet<SUCours> _SUCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TimeScheduleWeb> TimeScheduleWebs
        {
            get
            {
                if ((_TimeScheduleWebs == null))
                {
                    _TimeScheduleWebs = base.CreateObjectSet<TimeScheduleWeb>("TimeScheduleWebs");
                }
                return _TimeScheduleWebs;
            }
        }
        private ObjectSet<TimeScheduleWeb> _TimeScheduleWebs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CatalogBaseCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCatalogBaseCourses(CatalogBaseCours catalogBaseCours)
        {
            base.AddObject("CatalogBaseCourses", catalogBaseCours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ESFCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToESFCourses(ESFCours eSFCours)
        {
            base.AddObject("ESFCourses", eSFCours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SUCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSUCourses(SUCours sUCours)
        {
            base.AddObject("SUCourses", sUCours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TimeScheduleWebs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimeScheduleWebs(TimeScheduleWeb timeScheduleWeb)
        {
            base.AddObject("TimeScheduleWebs", timeScheduleWeb);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="semester">No Metadata Documentation available.</param>
        /// <param name="building">No Metadata Documentation available.</param>
        /// <param name="room">No Metadata Documentation available.</param>
        public ObjectResult<spTimeSchedSingleSpace_Result> spTimeSchedSingleSpace(global::System.String semester, global::System.String building, global::System.String room)
        {
            ObjectParameter semesterParameter;
            if (semester != null)
            {
                semesterParameter = new ObjectParameter("semester", semester);
            }
            else
            {
                semesterParameter = new ObjectParameter("semester", typeof(global::System.String));
            }
    
            ObjectParameter buildingParameter;
            if (building != null)
            {
                buildingParameter = new ObjectParameter("building", building);
            }
            else
            {
                buildingParameter = new ObjectParameter("building", typeof(global::System.String));
            }
    
            ObjectParameter roomParameter;
            if (room != null)
            {
                roomParameter = new ObjectParameter("room", room);
            }
            else
            {
                roomParameter = new ObjectParameter("room", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spTimeSchedSingleSpace_Result>("spTimeSchedSingleSpace", semesterParameter, buildingParameter, roomParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> spDistinctSemestersTS()
        {
            return base.ExecuteFunction<global::System.String>("spDistinctSemestersTS");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatalogModel", Name="CatalogBaseCours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CatalogBaseCours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CatalogBaseCours object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        /// <param name="courseTitle">Initial value of the CourseTitle property.</param>
        /// <param name="approvalDt">Initial value of the ApprovalDt property.</param>
        /// <param name="deactivationDt">Initial value of the DeactivationDt property.</param>
        /// <param name="minCredHrs">Initial value of the MinCredHrs property.</param>
        /// <param name="maxCredHrs">Initial value of the MaxCredHrs property.</param>
        /// <param name="profConsent">Initial value of the ProfConsent property.</param>
        /// <param name="crossListed">Initial value of the CrossListed property.</param>
        /// <param name="teachDept">Initial value of the TeachDept property.</param>
        /// <param name="comments">Initial value of the Comments property.</param>
        public static CatalogBaseCours CreateCatalogBaseCours(global::System.String courseID, global::System.String courseTitle, global::System.DateTime approvalDt, global::System.DateTime deactivationDt, global::System.Single minCredHrs, global::System.Single maxCredHrs, global::System.Boolean profConsent, global::System.String crossListed, global::System.String teachDept, global::System.String comments)
        {
            CatalogBaseCours catalogBaseCours = new CatalogBaseCours();
            catalogBaseCours.CourseID = courseID;
            catalogBaseCours.CourseTitle = courseTitle;
            catalogBaseCours.ApprovalDt = approvalDt;
            catalogBaseCours.DeactivationDt = deactivationDt;
            catalogBaseCours.MinCredHrs = minCredHrs;
            catalogBaseCours.MaxCredHrs = maxCredHrs;
            catalogBaseCours.ProfConsent = profConsent;
            catalogBaseCours.CrossListed = crossListed;
            catalogBaseCours.TeachDept = teachDept;
            catalogBaseCours.Comments = comments;
            return catalogBaseCours;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseTitle
        {
            get
            {
                return _CourseTitle;
            }
            set
            {
                OnCourseTitleChanging(value);
                ReportPropertyChanging("CourseTitle");
                _CourseTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CourseTitle");
                OnCourseTitleChanged();
            }
        }
        private global::System.String _CourseTitle;
        partial void OnCourseTitleChanging(global::System.String value);
        partial void OnCourseTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ApprovalDt
        {
            get
            {
                return _ApprovalDt;
            }
            set
            {
                OnApprovalDtChanging(value);
                ReportPropertyChanging("ApprovalDt");
                _ApprovalDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApprovalDt");
                OnApprovalDtChanged();
            }
        }
        private global::System.DateTime _ApprovalDt;
        partial void OnApprovalDtChanging(global::System.DateTime value);
        partial void OnApprovalDtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DeactivationDt
        {
            get
            {
                return _DeactivationDt;
            }
            set
            {
                OnDeactivationDtChanging(value);
                ReportPropertyChanging("DeactivationDt");
                _DeactivationDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeactivationDt");
                OnDeactivationDtChanged();
            }
        }
        private global::System.DateTime _DeactivationDt;
        partial void OnDeactivationDtChanging(global::System.DateTime value);
        partial void OnDeactivationDtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MinCredHrs
        {
            get
            {
                return _MinCredHrs;
            }
            set
            {
                OnMinCredHrsChanging(value);
                ReportPropertyChanging("MinCredHrs");
                _MinCredHrs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinCredHrs");
                OnMinCredHrsChanged();
            }
        }
        private global::System.Single _MinCredHrs;
        partial void OnMinCredHrsChanging(global::System.Single value);
        partial void OnMinCredHrsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaxCredHrs
        {
            get
            {
                return _MaxCredHrs;
            }
            set
            {
                OnMaxCredHrsChanging(value);
                ReportPropertyChanging("MaxCredHrs");
                _MaxCredHrs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxCredHrs");
                OnMaxCredHrsChanged();
            }
        }
        private global::System.Single _MaxCredHrs;
        partial void OnMaxCredHrsChanging(global::System.Single value);
        partial void OnMaxCredHrsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ProfConsent
        {
            get
            {
                return _ProfConsent;
            }
            set
            {
                OnProfConsentChanging(value);
                ReportPropertyChanging("ProfConsent");
                _ProfConsent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfConsent");
                OnProfConsentChanged();
            }
        }
        private global::System.Boolean _ProfConsent;
        partial void OnProfConsentChanging(global::System.Boolean value);
        partial void OnProfConsentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrossListed
        {
            get
            {
                return _CrossListed;
            }
            set
            {
                OnCrossListedChanging(value);
                ReportPropertyChanging("CrossListed");
                _CrossListed = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CrossListed");
                OnCrossListedChanged();
            }
        }
        private global::System.String _CrossListed;
        partial void OnCrossListedChanging(global::System.String value);
        partial void OnCrossListedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeachDept
        {
            get
            {
                return _TeachDept;
            }
            set
            {
                OnTeachDeptChanging(value);
                ReportPropertyChanging("TeachDept");
                _TeachDept = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TeachDept");
                OnTeachDeptChanged();
            }
        }
        private global::System.String _TeachDept;
        partial void OnTeachDeptChanging(global::System.String value);
        partial void OnTeachDeptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatalogModel", Name="ESFCours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ESFCours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ESFCours object.
        /// </summary>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        public static ESFCours CreateESFCours(global::System.String courseId)
        {
            ESFCours eSFCours = new ESFCours();
            eSFCours.CourseId = courseId;
            return eSFCours;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                if (_CourseId != value)
                {
                    OnCourseIdChanging(value);
                    ReportPropertyChanging("CourseId");
                    _CourseId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseId");
                    OnCourseIdChanged();
                }
            }
        }
        private global::System.String _CourseId;
        partial void OnCourseIdChanging(global::System.String value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NiceTitle
        {
            get
            {
                return _NiceTitle;
            }
            set
            {
                OnNiceTitleChanging(value);
                ReportPropertyChanging("NiceTitle");
                _NiceTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NiceTitle");
                OnNiceTitleChanged();
            }
        }
        private global::System.String _NiceTitle;
        partial void OnNiceTitleChanging(global::System.String value);
        partial void OnNiceTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseDesc
        {
            get
            {
                return _CourseDesc;
            }
            set
            {
                OnCourseDescChanging(value);
                ReportPropertyChanging("CourseDesc");
                _CourseDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseDesc");
                OnCourseDescChanged();
            }
        }
        private global::System.String _CourseDesc;
        partial void OnCourseDescChanging(global::System.String value);
        partial void OnCourseDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebUrl
        {
            get
            {
                return _WebUrl;
            }
            set
            {
                OnWebUrlChanging(value);
                ReportPropertyChanging("WebUrl");
                _WebUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebUrl");
                OnWebUrlChanged();
            }
        }
        private global::System.String _WebUrl;
        partial void OnWebUrlChanging(global::System.String value);
        partial void OnWebUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GenEd
        {
            get
            {
                return _GenEd;
            }
            set
            {
                OnGenEdChanging(value);
                ReportPropertyChanging("GenEd");
                _GenEd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GenEd");
                OnGenEdChanged();
            }
        }
        private global::System.String _GenEd;
        partial void OnGenEdChanging(global::System.String value);
        partial void OnGenEdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NiceNotes
        {
            get
            {
                return _NiceNotes;
            }
            set
            {
                OnNiceNotesChanging(value);
                ReportPropertyChanging("NiceNotes");
                _NiceNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NiceNotes");
                OnNiceNotesChanged();
            }
        }
        private global::System.String _NiceNotes;
        partial void OnNiceNotesChanging(global::System.String value);
        partial void OnNiceNotesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatalogModel", Name="SUCours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SUCours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SUCours object.
        /// </summary>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="credits">Initial value of the Credits property.</param>
        /// <param name="genEds">Initial value of the GenEds property.</param>
        public static SUCours CreateSUCours(global::System.String courseId, global::System.String title, global::System.Single credits, global::System.String genEds)
        {
            SUCours sUCours = new SUCours();
            sUCours.CourseId = courseId;
            sUCours.Title = title;
            sUCours.Credits = credits;
            sUCours.GenEds = genEds;
            return sUCours;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                if (_CourseId != value)
                {
                    OnCourseIdChanging(value);
                    ReportPropertyChanging("CourseId");
                    _CourseId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseId");
                    OnCourseIdChanged();
                }
            }
        }
        private global::System.String _CourseId;
        partial void OnCourseIdChanging(global::System.String value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                if (_Title != value)
                {
                    OnTitleChanging(value);
                    ReportPropertyChanging("Title");
                    _Title = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Credits
        {
            get
            {
                return _Credits;
            }
            set
            {
                if (_Credits != value)
                {
                    OnCreditsChanging(value);
                    ReportPropertyChanging("Credits");
                    _Credits = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Credits");
                    OnCreditsChanged();
                }
            }
        }
        private global::System.Single _Credits;
        partial void OnCreditsChanging(global::System.Single value);
        partial void OnCreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GenEds
        {
            get
            {
                return _GenEds;
            }
            set
            {
                if (_GenEds != value)
                {
                    OnGenEdsChanging(value);
                    ReportPropertyChanging("GenEds");
                    _GenEds = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GenEds");
                    OnGenEdsChanged();
                }
            }
        }
        private global::System.String _GenEds;
        partial void OnGenEdsChanging(global::System.String value);
        partial void OnGenEdsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatalogModel", Name="TimeScheduleWeb")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TimeScheduleWeb : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TimeScheduleWeb object.
        /// </summary>
        /// <param name="semester">Initial value of the Semester property.</param>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        /// <param name="sectNbr">Initial value of the SectNbr property.</param>
        /// <param name="mtgKey">Initial value of the MtgKey property.</param>
        /// <param name="profKey">Initial value of the ProfKey property.</param>
        /// <param name="generalCourseTitle">Initial value of the GeneralCourseTitle property.</param>
        /// <param name="sectionCourseTitle">Initial value of the SectionCourseTitle property.</param>
        /// <param name="minCredHrs">Initial value of the MinCredHrs property.</param>
        /// <param name="maxCredHrs">Initial value of the MaxCredHrs property.</param>
        /// <param name="referenceNbr">Initial value of the ReferenceNbr property.</param>
        /// <param name="generalProfConsent">Initial value of the GeneralProfConsent property.</param>
        /// <param name="sectionProfConsent">Initial value of the SectionProfConsent property.</param>
        /// <param name="sectionBeginDt">Initial value of the SectionBeginDt property.</param>
        /// <param name="sectionEndDt">Initial value of the SectionEndDt property.</param>
        /// <param name="generalCrossListed">Initial value of the GeneralCrossListed property.</param>
        /// <param name="generalComments">Initial value of the GeneralComments property.</param>
        /// <param name="sectionComments">Initial value of the SectionComments property.</param>
        /// <param name="sectionHighSchool">Initial value of the SectionHighSchool property.</param>
        /// <param name="monday">Initial value of the Monday property.</param>
        /// <param name="tuesday">Initial value of the Tuesday property.</param>
        /// <param name="wednesday">Initial value of the Wednesday property.</param>
        /// <param name="thursday">Initial value of the Thursday property.</param>
        /// <param name="friday">Initial value of the Friday property.</param>
        /// <param name="saturday">Initial value of the Saturday property.</param>
        /// <param name="sunday">Initial value of the Sunday property.</param>
        /// <param name="dayUnspecified">Initial value of the DayUnspecified property.</param>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        /// <param name="endTime">Initial value of the EndTime property.</param>
        /// <param name="building">Initial value of the Building property.</param>
        /// <param name="room">Initial value of the Room property.</param>
        /// <param name="instructor">Initial value of the Instructor property.</param>
        public static TimeScheduleWeb CreateTimeScheduleWeb(global::System.String semester, global::System.String courseID, global::System.String sectNbr, global::System.String mtgKey, global::System.String profKey, global::System.String generalCourseTitle, global::System.String sectionCourseTitle, global::System.Single minCredHrs, global::System.Single maxCredHrs, global::System.Int32 referenceNbr, global::System.Boolean generalProfConsent, global::System.Boolean sectionProfConsent, global::System.DateTime sectionBeginDt, global::System.DateTime sectionEndDt, global::System.String generalCrossListed, global::System.String generalComments, global::System.String sectionComments, global::System.String sectionHighSchool, global::System.Single monday, global::System.Single tuesday, global::System.Single wednesday, global::System.Single thursday, global::System.Single friday, global::System.Single saturday, global::System.Single sunday, global::System.Single dayUnspecified, global::System.DateTime startTime, global::System.DateTime endTime, global::System.String building, global::System.String room, global::System.String instructor)
        {
            TimeScheduleWeb timeScheduleWeb = new TimeScheduleWeb();
            timeScheduleWeb.Semester = semester;
            timeScheduleWeb.CourseID = courseID;
            timeScheduleWeb.SectNbr = sectNbr;
            timeScheduleWeb.MtgKey = mtgKey;
            timeScheduleWeb.ProfKey = profKey;
            timeScheduleWeb.GeneralCourseTitle = generalCourseTitle;
            timeScheduleWeb.SectionCourseTitle = sectionCourseTitle;
            timeScheduleWeb.MinCredHrs = minCredHrs;
            timeScheduleWeb.MaxCredHrs = maxCredHrs;
            timeScheduleWeb.ReferenceNbr = referenceNbr;
            timeScheduleWeb.GeneralProfConsent = generalProfConsent;
            timeScheduleWeb.SectionProfConsent = sectionProfConsent;
            timeScheduleWeb.SectionBeginDt = sectionBeginDt;
            timeScheduleWeb.SectionEndDt = sectionEndDt;
            timeScheduleWeb.GeneralCrossListed = generalCrossListed;
            timeScheduleWeb.GeneralComments = generalComments;
            timeScheduleWeb.SectionComments = sectionComments;
            timeScheduleWeb.SectionHighSchool = sectionHighSchool;
            timeScheduleWeb.Monday = monday;
            timeScheduleWeb.Tuesday = tuesday;
            timeScheduleWeb.Wednesday = wednesday;
            timeScheduleWeb.Thursday = thursday;
            timeScheduleWeb.Friday = friday;
            timeScheduleWeb.Saturday = saturday;
            timeScheduleWeb.Sunday = sunday;
            timeScheduleWeb.DayUnspecified = dayUnspecified;
            timeScheduleWeb.StartTime = startTime;
            timeScheduleWeb.EndTime = endTime;
            timeScheduleWeb.Building = building;
            timeScheduleWeb.Room = room;
            timeScheduleWeb.Instructor = instructor;
            return timeScheduleWeb;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                if (_Semester != value)
                {
                    OnSemesterChanging(value);
                    ReportPropertyChanging("Semester");
                    _Semester = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Semester");
                    OnSemesterChanged();
                }
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SectNbr
        {
            get
            {
                return _SectNbr;
            }
            set
            {
                if (_SectNbr != value)
                {
                    OnSectNbrChanging(value);
                    ReportPropertyChanging("SectNbr");
                    _SectNbr = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SectNbr");
                    OnSectNbrChanged();
                }
            }
        }
        private global::System.String _SectNbr;
        partial void OnSectNbrChanging(global::System.String value);
        partial void OnSectNbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MtgKey
        {
            get
            {
                return _MtgKey;
            }
            set
            {
                if (_MtgKey != value)
                {
                    OnMtgKeyChanging(value);
                    ReportPropertyChanging("MtgKey");
                    _MtgKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MtgKey");
                    OnMtgKeyChanged();
                }
            }
        }
        private global::System.String _MtgKey;
        partial void OnMtgKeyChanging(global::System.String value);
        partial void OnMtgKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProfKey
        {
            get
            {
                return _ProfKey;
            }
            set
            {
                if (_ProfKey != value)
                {
                    OnProfKeyChanging(value);
                    ReportPropertyChanging("ProfKey");
                    _ProfKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ProfKey");
                    OnProfKeyChanged();
                }
            }
        }
        private global::System.String _ProfKey;
        partial void OnProfKeyChanging(global::System.String value);
        partial void OnProfKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GeneralCourseTitle
        {
            get
            {
                return _GeneralCourseTitle;
            }
            set
            {
                OnGeneralCourseTitleChanging(value);
                ReportPropertyChanging("GeneralCourseTitle");
                _GeneralCourseTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GeneralCourseTitle");
                OnGeneralCourseTitleChanged();
            }
        }
        private global::System.String _GeneralCourseTitle;
        partial void OnGeneralCourseTitleChanging(global::System.String value);
        partial void OnGeneralCourseTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SectionCourseTitle
        {
            get
            {
                return _SectionCourseTitle;
            }
            set
            {
                OnSectionCourseTitleChanging(value);
                ReportPropertyChanging("SectionCourseTitle");
                _SectionCourseTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SectionCourseTitle");
                OnSectionCourseTitleChanged();
            }
        }
        private global::System.String _SectionCourseTitle;
        partial void OnSectionCourseTitleChanging(global::System.String value);
        partial void OnSectionCourseTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MinCredHrs
        {
            get
            {
                return _MinCredHrs;
            }
            set
            {
                OnMinCredHrsChanging(value);
                ReportPropertyChanging("MinCredHrs");
                _MinCredHrs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinCredHrs");
                OnMinCredHrsChanged();
            }
        }
        private global::System.Single _MinCredHrs;
        partial void OnMinCredHrsChanging(global::System.Single value);
        partial void OnMinCredHrsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaxCredHrs
        {
            get
            {
                return _MaxCredHrs;
            }
            set
            {
                OnMaxCredHrsChanging(value);
                ReportPropertyChanging("MaxCredHrs");
                _MaxCredHrs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxCredHrs");
                OnMaxCredHrsChanged();
            }
        }
        private global::System.Single _MaxCredHrs;
        partial void OnMaxCredHrsChanging(global::System.Single value);
        partial void OnMaxCredHrsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReferenceNbr
        {
            get
            {
                return _ReferenceNbr;
            }
            set
            {
                OnReferenceNbrChanging(value);
                ReportPropertyChanging("ReferenceNbr");
                _ReferenceNbr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReferenceNbr");
                OnReferenceNbrChanged();
            }
        }
        private global::System.Int32 _ReferenceNbr;
        partial void OnReferenceNbrChanging(global::System.Int32 value);
        partial void OnReferenceNbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean GeneralProfConsent
        {
            get
            {
                return _GeneralProfConsent;
            }
            set
            {
                OnGeneralProfConsentChanging(value);
                ReportPropertyChanging("GeneralProfConsent");
                _GeneralProfConsent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralProfConsent");
                OnGeneralProfConsentChanged();
            }
        }
        private global::System.Boolean _GeneralProfConsent;
        partial void OnGeneralProfConsentChanging(global::System.Boolean value);
        partial void OnGeneralProfConsentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SectionProfConsent
        {
            get
            {
                return _SectionProfConsent;
            }
            set
            {
                OnSectionProfConsentChanging(value);
                ReportPropertyChanging("SectionProfConsent");
                _SectionProfConsent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionProfConsent");
                OnSectionProfConsentChanged();
            }
        }
        private global::System.Boolean _SectionProfConsent;
        partial void OnSectionProfConsentChanging(global::System.Boolean value);
        partial void OnSectionProfConsentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SectionBeginDt
        {
            get
            {
                return _SectionBeginDt;
            }
            set
            {
                OnSectionBeginDtChanging(value);
                ReportPropertyChanging("SectionBeginDt");
                _SectionBeginDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionBeginDt");
                OnSectionBeginDtChanged();
            }
        }
        private global::System.DateTime _SectionBeginDt;
        partial void OnSectionBeginDtChanging(global::System.DateTime value);
        partial void OnSectionBeginDtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SectionEndDt
        {
            get
            {
                return _SectionEndDt;
            }
            set
            {
                OnSectionEndDtChanging(value);
                ReportPropertyChanging("SectionEndDt");
                _SectionEndDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionEndDt");
                OnSectionEndDtChanged();
            }
        }
        private global::System.DateTime _SectionEndDt;
        partial void OnSectionEndDtChanging(global::System.DateTime value);
        partial void OnSectionEndDtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GeneralCrossListed
        {
            get
            {
                return _GeneralCrossListed;
            }
            set
            {
                OnGeneralCrossListedChanging(value);
                ReportPropertyChanging("GeneralCrossListed");
                _GeneralCrossListed = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GeneralCrossListed");
                OnGeneralCrossListedChanged();
            }
        }
        private global::System.String _GeneralCrossListed;
        partial void OnGeneralCrossListedChanging(global::System.String value);
        partial void OnGeneralCrossListedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GeneralComments
        {
            get
            {
                return _GeneralComments;
            }
            set
            {
                OnGeneralCommentsChanging(value);
                ReportPropertyChanging("GeneralComments");
                _GeneralComments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GeneralComments");
                OnGeneralCommentsChanged();
            }
        }
        private global::System.String _GeneralComments;
        partial void OnGeneralCommentsChanging(global::System.String value);
        partial void OnGeneralCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SectionComments
        {
            get
            {
                return _SectionComments;
            }
            set
            {
                OnSectionCommentsChanging(value);
                ReportPropertyChanging("SectionComments");
                _SectionComments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SectionComments");
                OnSectionCommentsChanged();
            }
        }
        private global::System.String _SectionComments;
        partial void OnSectionCommentsChanging(global::System.String value);
        partial void OnSectionCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SectionHighSchool
        {
            get
            {
                return _SectionHighSchool;
            }
            set
            {
                OnSectionHighSchoolChanging(value);
                ReportPropertyChanging("SectionHighSchool");
                _SectionHighSchool = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SectionHighSchool");
                OnSectionHighSchoolChanged();
            }
        }
        private global::System.String _SectionHighSchool;
        partial void OnSectionHighSchoolChanging(global::System.String value);
        partial void OnSectionHighSchoolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Monday
        {
            get
            {
                return _Monday;
            }
            set
            {
                OnMondayChanging(value);
                ReportPropertyChanging("Monday");
                _Monday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monday");
                OnMondayChanged();
            }
        }
        private global::System.Single _Monday;
        partial void OnMondayChanging(global::System.Single value);
        partial void OnMondayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Tuesday
        {
            get
            {
                return _Tuesday;
            }
            set
            {
                OnTuesdayChanging(value);
                ReportPropertyChanging("Tuesday");
                _Tuesday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tuesday");
                OnTuesdayChanged();
            }
        }
        private global::System.Single _Tuesday;
        partial void OnTuesdayChanging(global::System.Single value);
        partial void OnTuesdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Wednesday
        {
            get
            {
                return _Wednesday;
            }
            set
            {
                OnWednesdayChanging(value);
                ReportPropertyChanging("Wednesday");
                _Wednesday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Wednesday");
                OnWednesdayChanged();
            }
        }
        private global::System.Single _Wednesday;
        partial void OnWednesdayChanging(global::System.Single value);
        partial void OnWednesdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Thursday
        {
            get
            {
                return _Thursday;
            }
            set
            {
                OnThursdayChanging(value);
                ReportPropertyChanging("Thursday");
                _Thursday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Thursday");
                OnThursdayChanged();
            }
        }
        private global::System.Single _Thursday;
        partial void OnThursdayChanging(global::System.Single value);
        partial void OnThursdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Friday
        {
            get
            {
                return _Friday;
            }
            set
            {
                OnFridayChanging(value);
                ReportPropertyChanging("Friday");
                _Friday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Friday");
                OnFridayChanged();
            }
        }
        private global::System.Single _Friday;
        partial void OnFridayChanging(global::System.Single value);
        partial void OnFridayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Saturday
        {
            get
            {
                return _Saturday;
            }
            set
            {
                OnSaturdayChanging(value);
                ReportPropertyChanging("Saturday");
                _Saturday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Saturday");
                OnSaturdayChanged();
            }
        }
        private global::System.Single _Saturday;
        partial void OnSaturdayChanging(global::System.Single value);
        partial void OnSaturdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Sunday
        {
            get
            {
                return _Sunday;
            }
            set
            {
                OnSundayChanging(value);
                ReportPropertyChanging("Sunday");
                _Sunday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sunday");
                OnSundayChanged();
            }
        }
        private global::System.Single _Sunday;
        partial void OnSundayChanging(global::System.Single value);
        partial void OnSundayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single DayUnspecified
        {
            get
            {
                return _DayUnspecified;
            }
            set
            {
                OnDayUnspecifiedChanging(value);
                ReportPropertyChanging("DayUnspecified");
                _DayUnspecified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayUnspecified");
                OnDayUnspecifiedChanged();
            }
        }
        private global::System.Single _DayUnspecified;
        partial void OnDayUnspecifiedChanging(global::System.Single value);
        partial void OnDayUnspecifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Building
        {
            get
            {
                return _Building;
            }
            set
            {
                OnBuildingChanging(value);
                ReportPropertyChanging("Building");
                _Building = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Building");
                OnBuildingChanged();
            }
        }
        private global::System.String _Building;
        partial void OnBuildingChanging(global::System.String value);
        partial void OnBuildingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Room
        {
            get
            {
                return _Room;
            }
            set
            {
                OnRoomChanging(value);
                ReportPropertyChanging("Room");
                _Room = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Room");
                OnRoomChanged();
            }
        }
        private global::System.String _Room;
        partial void OnRoomChanging(global::System.String value);
        partial void OnRoomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Instructor
        {
            get
            {
                return _Instructor;
            }
            set
            {
                OnInstructorChanging(value);
                ReportPropertyChanging("Instructor");
                _Instructor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Instructor");
                OnInstructorChanged();
            }
        }
        private global::System.String _Instructor;
        partial void OnInstructorChanging(global::System.String value);
        partial void OnInstructorChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CatalogModel", Name="spTimeSchedSingleSpace_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spTimeSchedSingleSpace_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private global::System.String _CourseId;
        partial void OnCourseIdChanging(global::System.String value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EventDate
        {
            get
            {
                return _EventDate;
            }
            set
            {
                OnEventDateChanging(value);
                ReportPropertyChanging("EventDate");
                _EventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventDate");
                OnEventDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EventDate;
        partial void OnEventDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEventDateChanged();

        #endregion

    }

    #endregion

    
}
