//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogBaseCours
    {
        public string CourseID { get; set; }
        public string CourseTitle { get; set; }
        public System.DateTime ApprovalDt { get; set; }
        public System.DateTime DeactivationDt { get; set; }
        public float MinCredHrs { get; set; }
        public float MaxCredHrs { get; set; }
        public bool ProfConsent { get; set; }
        public string CrossListed { get; set; }
        public string TeachDept { get; set; }
        public string Comments { get; set; }
    }
}
