//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESFCours
    {
        public string CourseId { get; set; }
        public string NiceTitle { get; set; }
        public string CourseDesc { get; set; }
        public string WebUrl { get; set; }
        public string GenEd { get; set; }
        public string NiceNotes { get; set; }
    }
}
