//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCours
    {
        public string CourseId { get; set; }
        public string Title { get; set; }
        public float Credits { get; set; }
        public string GenEds { get; set; }
    }
}
