//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeScheduleWeb
    {
        public string Semester { get; set; }
        public string CourseID { get; set; }
        public string SectNbr { get; set; }
        public string MtgKey { get; set; }
        public string ProfKey { get; set; }
        public string GeneralCourseTitle { get; set; }
        public string SectionCourseTitle { get; set; }
        public float MinCredHrs { get; set; }
        public float MaxCredHrs { get; set; }
        public int ReferenceNbr { get; set; }
        public bool GeneralProfConsent { get; set; }
        public bool SectionProfConsent { get; set; }
        public System.DateTime SectionBeginDt { get; set; }
        public System.DateTime SectionEndDt { get; set; }
        public string GeneralCrossListed { get; set; }
        public string GeneralComments { get; set; }
        public string SectionComments { get; set; }
        public string SectionHighSchool { get; set; }
        public float Monday { get; set; }
        public float Tuesday { get; set; }
        public float Wednesday { get; set; }
        public float Thursday { get; set; }
        public float Friday { get; set; }
        public float Saturday { get; set; }
        public float Sunday { get; set; }
        public float DayUnspecified { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public string Instructor { get; set; }
    }
}
